name: Deploy NGINX to AKS

on:
  push:
    branches:
      - main
      - devops

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Set up Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Get AKS Credentials
      run: az aks get-credentials --resource-group vuleRG --name vuleAKS --overwrite-existing

    - name: Deploy NGINX to AKS
      run: |
        kubectl apply -f nginx-deployment.yaml
        kubectl apply -f nginx-service.yaml
